name: 'CheckMedal'

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  actions: write

jobs:
  medal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Load Cache
        uses: actions/cache/restore@v3
        with:
          key: ${{ runner.os }}_cache.json
          path: cache.json
      - name: Check Medal
        run: |
          npm install
          npm install request --save
          npm run start
        env:
          KAME_COOKIES: ${{ secrets.KAME_COOKIES }}
          KAME_CHID: ${{ secrets.KAME_CHID }}
          KAME_TOKEN: ${{ secrets.KAME_TOKEN }}
          KAME_CRON: ${{ secrets.KAME_CRON }}
      - name: Clear cache
        uses: actions/github-script@v6
        with:
          script: |
            console.log("About to clear")
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              console.log(cache)
              github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id,
              })
            }
            console.log("Clear completed")
      - name: Save cache
        uses: actions/cache/save@v3
        # if: always()
        with:
          key: ${{ runner.os }}_cache.json
          path: cache.json